set -g base-index 1
set-window-option -g mode-keys vi
set-option -sg escape-time 10
set-option -g focus-events on
set-option -g default-terminal "tmux-256color"
set-option -as terminal-features ",xterm-256color:RGB"

bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

set -g status-right "#(~/.config/tmux/scripts/git-branch.sh | cut -c -16) | %a %Y-%m-%d %H:%M"
